default_context:
  project_name: 'VF2'
  project_slug: 'vf2'
  domain_main: 'vf2.io'
  domain_staging: 'stag.vf2.io'
  docker_swarm_stack_name_main: 'vf2-io'
  docker_swarm_stack_name_staging: 'stag-vf2-io'
  secret_key: '83581d2034b9881665f98ef860fa7c64c08b1912ba2303cb574e45aad4a0dcbd'
  first_superuser: 'admin@vf2.io'
  first_superuser_password: '21530530f1911674e1f20ff532747a2e0852b546b480667ed0effe188d079321'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.vf2.io", "https://stag.vf2.io", "https://vf2.io"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@vf2.io'
  postgres_password: '802b3c1137e979955993a2fe7d7f82df1422034b24235fc880d605014f2a1313'
  pgadmin_default_user: 'admin@vf2.io'
  pgadmin_default_user_password: '21530530f1911674e1f20ff532747a2e0852b546b480667ed0effe188d079321'
  traefik_constraint_tag: 'vf2.io'
  traefik_constraint_tag_staging: 'stag.vf2.io'
  traefik_public_constraint_tag: 'pub.vf2.io'
  flower_auth: 'admin:21530530f1911674e1f20ff532747a2e0852b546b480667ed0effe188d079321'
  sentry_dsn: ''
  docker_image_prefix: 'ghcr.io/willongithub/vue-fastapi-firebase/'
  docker_image_backend: 'ghcr.io/willongithub/vue-fastapi-firebase/backend'
  docker_image_celeryworker: 'ghcr.io/willongithub/vue-fastapi-firebase/celeryworker'
  docker_image_frontend: 'ghcr.io/willongithub/vue-fastapi-firebase/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
